name: Build, Test and Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install --prefix ./sdk
      - name: Build 
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm run build --prefix ./sdk
      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          DEPLOY_DIR: sdk/
          SRC_PACKAGE_DIR: sdk/
  build-demo-app:
    needs: publish
    name: Build Demo App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: frontegg/nodejs-sdk-demo-app
          file: demo-app/Dockerfile
